"""user auto rest preference

Revision ID: 1542b8c6b082
Revises: d07f1f974f04
Create Date: 2026-09-28 21:43:58.664168

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1542b8c6b082"
down_revision: str | Sequence[str] | None = "d07f1f974f04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("auto_rest", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auto_rest")
    # ### end Alembic commands ###
