"""auth password tracking and persistent sessions

Revision ID: 2264f4c03eda
Revises: 58ee1daea71b
Create Date: 2026-09-28 19:55:37.033412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2264f4c03eda"
down_revision: str | Sequence[str] | None = "58ee1daea71b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column("persistent", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "users", sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK constraints.
    op.create_check_constraint(op.f("ck_users_email_lowercase"), "users", "email = lower(email)")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_users_email_lowercase"), "users", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_changed_at")
    op.drop_column("refresh_tokens", "persistent")
    # ### end Alembic commands ###
