"""session local date and done exercises

Revision ID: d07f1f974f04
Revises: dfe4dfebc513
Create Date: 2026-09-28 20:51:33.942703

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d07f1f974f04"
down_revision: str | Sequence[str] | None = "dfe4dfebc513"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing sessions (none were ever written before phase 4) get their UTC start date.
    op.add_column("workout_sessions", sa.Column("local_date", sa.Date(), nullable=True))
    op.execute("UPDATE workout_sessions SET local_date = started_at::date")
    op.alter_column("workout_sessions", "local_date", nullable=False)
    op.add_column(
        "workout_sessions",
        sa.Column(
            "done_exercise_ids", sa.ARRAY(sa.Uuid()), server_default=sa.text("'{}'"), nullable=False
        ),
    )
    op.create_index(
        "uq_workout_sessions_user_day_date",
        "workout_sessions",
        ["user_id", "day_id", "local_date"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_workout_sessions_user_day_date", table_name="workout_sessions")
    op.drop_column("workout_sessions", "done_exercise_ids")
    op.drop_column("workout_sessions", "local_date")
    # ### end Alembic commands ###
