"""files, plan source file and exercise rest

Revision ID: dfe4dfebc513
Revises: 2264f4c03eda
Create Date: 2026-09-28 20:39:34.991591

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfe4dfebc513"
down_revision: str | Sequence[str] | None = "2264f4c03eda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("workout_pdf", "health_export", name="filekind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('workout_pdf', 'health_export')", name=op.f("ck_files_kind")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_files_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("object_key", name=op.f("uq_files_object_key")),
    )
    op.create_index(op.f("ix_files_user_id"), "files", ["user_id"], unique=False)
    op.add_column("exercises", sa.Column("rest_seconds", sa.SmallInteger(), nullable=True))
    op.add_column("exercises", sa.Column("rest_max_seconds", sa.SmallInteger(), nullable=True))
    op.alter_column(
        "exercises",
        "muscle_group",
        existing_type=sa.VARCHAR(length=60),
        type_=sa.Enum(
            "warmup",
            "chest",
            "back",
            "shoulders",
            "biceps",
            "triceps",
            "forearms",
            "abs",
            "quads",
            "hamstrings",
            "glutes",
            "adductors",
            "calves",
            "cardio",
            "other",
            name="musclegroup",
            native_enum=False,
            length=16,
        ),
        existing_nullable=True,
    )
    op.add_column("workout_plans", sa.Column("source_file_id", sa.Uuid(), nullable=True))
    op.add_column("workout_plans", sa.Column("valid_until", sa.Date(), nullable=True))
    op.create_index(
        op.f("ix_workout_plans_source_file_id"), "workout_plans", ["source_file_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_workout_plans_source_file_id_files"),
        "workout_plans",
        "files",
        ["source_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workout_plans", "source_file_key")
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK constraints.
    groups = ", ".join(
        f"'{g}'"
        for g in (
            "warmup", "chest", "back", "shoulders", "biceps", "triceps", "forearms", "abs",
            "quads", "hamstrings", "glutes", "adductors", "calves", "cardio", "other",
        )
    )  # fmt: skip
    op.create_check_constraint(
        op.f("ck_exercises_muscle_group"), "exercises", f"muscle_group IN ({groups})"
    )
    op.create_check_constraint(
        op.f("ck_exercises_rest_non_negative"), "exercises", "rest_seconds >= 0"
    )
    op.create_check_constraint(
        op.f("ck_exercises_rest_range"), "exercises", "rest_max_seconds >= rest_seconds"
    )


def downgrade() -> None:
    """Downgrade schema."""
    for name in ("ck_exercises_rest_range", "ck_exercises_rest_non_negative"):
        op.drop_constraint(op.f(name), "exercises", type_="check")
    op.drop_constraint(op.f("ck_exercises_muscle_group"), "exercises", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_plans",
        sa.Column("source_file_key", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_workout_plans_source_file_id_files"), "workout_plans", type_="foreignkey"
    )
    op.drop_index(op.f("ix_workout_plans_source_file_id"), table_name="workout_plans")
    op.drop_column("workout_plans", "valid_until")
    op.drop_column("workout_plans", "source_file_id")
    op.alter_column(
        "exercises",
        "muscle_group",
        existing_type=sa.Enum(
            "warmup",
            "chest",
            "back",
            "shoulders",
            "biceps",
            "triceps",
            "forearms",
            "abs",
            "quads",
            "hamstrings",
            "glutes",
            "adductors",
            "calves",
            "cardio",
            "other",
            name="musclegroup",
            native_enum=False,
            length=16,
        ),
        type_=sa.VARCHAR(length=60),
        existing_nullable=True,
    )
    op.drop_column("exercises", "rest_max_seconds")
    op.drop_column("exercises", "rest_seconds")
    op.drop_index(op.f("ix_files_user_id"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
