"""body measurements

Weighings (typed in, or read from a smart scale) and the three profile fields the scale's body
composition is worked out from. Only additions: the previous release doesn't see any of it.

Revision ID: ec1c3006fdb5
Revises: 0e9d0dbd3dac
Create Date: 2026-10-01 22:40:03.751775

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec1c3006fdb5"
down_revision: str | Sequence[str] | None = "0e9d0dbd3dac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_measurements",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "scale", name="measurementsource", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("impedance", sa.SmallInteger(), nullable=True),
        sa.Column("body_fat_pct", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'scale')", name=op.f("ck_body_measurements_source")
        ),
        sa.CheckConstraint(
            "weight BETWEEN 10 AND 300", name=op.f("ck_body_measurements_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_body_measurements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_measurements")),
    )
    op.create_index(
        "ix_body_measurements_user_time",
        "body_measurements",
        ["user_id", "measured_at"],
        unique=False,
    )
    op.create_index(
        "uq_body_measurements_user_source_time",
        "body_measurements",
        ["user_id", "source", "measured_at"],
        unique=True,
    )
    op.add_column("users", sa.Column("height_cm", sa.SmallInteger(), nullable=True))
    op.add_column("users", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "sex",
            sa.Enum("male", "female", name="sex", native_enum=False, length=16),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't see CHECK constraints on an existing table.
    op.create_check_constraint(op.f("ck_users_sex"), "users", "sex IN ('male', 'female')")
    op.create_check_constraint(
        op.f("ck_users_height_cm_range"), "users", "height_cm BETWEEN 50 AND 260"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_users_height_cm_range"), "users", type_="check")
    op.drop_constraint(op.f("ck_users_sex"), "users", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sex")
    op.drop_column("users", "birth_date")
    op.drop_column("users", "height_cm")
    op.drop_index("uq_body_measurements_user_source_time", table_name="body_measurements")
    op.drop_index("ix_body_measurements_user_time", table_name="body_measurements")
    op.drop_table("body_measurements")
    # ### end Alembic commands ###
