"""profile photo

Revision ID: 13c889359b01
Revises: 4321f75a15a6
Create Date: 2026-10-01 20:45:38.873047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13c889359b01"
down_revision: str | Sequence[str] | None = "4321f75a15a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_file_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_avatar_file_id_files"),
        "users",
        "files",
        ["avatar_file_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't see CHECK constraints: files can now be of kind "avatar".
    op.drop_constraint(op.f("ck_files_kind"), "files", type_="check")
    op.create_check_constraint(
        op.f("ck_files_kind"), "files", "kind IN ('workout_pdf', 'health_export', 'avatar')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # The rows go, their objects stay in storage (users/{id}/avatar/…): remove them by hand.
    op.execute("DELETE FROM files WHERE kind = 'avatar'")
    op.drop_constraint(op.f("ck_files_kind"), "files", type_="check")
    op.create_check_constraint(
        op.f("ck_files_kind"), "files", "kind IN ('workout_pdf', 'health_export')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_avatar_file_id_files"), "users", type_="foreignkey")
    op.drop_column("users", "avatar_file_id")
    # ### end Alembic commands ###
