"""initial schema

Revision ID: 58ee1daea71b
Revises:
Create Date: 2026-09-28 19:21:57.933987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58ee1daea71b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "language",
            sa.Enum("pt", "en", "es", name="language", native_enum=False, length=16),
            server_default="pt",
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=64), server_default="Europe/Lisbon", nullable=False),
        sa.Column(
            "unit",
            sa.Enum("kg", "lb", name="weightunit", native_enum=False, length=16),
            server_default="kg",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("language IN ('pt', 'en', 'es')", name=op.f("ck_users_language")),
        sa.CheckConstraint("unit IN ('kg', 'lb')", name=op.f("ck_users_unit")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "workout_plans",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("source_file_key", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workout_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_plans")),
    )
    op.create_index(op.f("ix_workout_plans_user_id"), "workout_plans", ["user_id"], unique=False)
    op.create_index(
        "uq_workout_plans_one_active_per_user",
        "workout_plans",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "workout_days",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_workout_days_weekday_range")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["workout_plans.id"],
            name=op.f("fk_workout_days_plan_id_workout_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_days")),
    )
    op.create_index(op.f("ix_workout_days_plan_id"), "workout_days", ["plan_id"], unique=False)
    op.create_table(
        "exercises",
        sa.Column("day_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("muscle_group", sa.String(length=60), nullable=True),
        sa.Column("sets", sa.SmallInteger(), nullable=True),
        sa.Column("reps", sa.String(length=32), nullable=True),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("sets > 0", name=op.f("ck_exercises_sets_positive")),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["workout_days.id"],
            name=op.f("fk_exercises_day_id_workout_days"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
    )
    op.create_index(op.f("ix_exercises_day_id"), "exercises", ["day_id"], unique=False)
    op.create_table(
        "workout_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day_id", sa.Uuid(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["workout_days.id"],
            name=op.f("fk_workout_sessions_day_id_workout_days"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workout_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sessions")),
    )
    op.create_index(
        op.f("ix_workout_sessions_day_id"), "workout_sessions", ["day_id"], unique=False
    )
    op.create_index(
        op.f("ix_workout_sessions_user_id"), "workout_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "exercise_logs",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("reps", sa.SmallInteger(), nullable=False),
        sa.Column("set_number", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("reps > 0", name=op.f("ck_exercise_logs_reps_positive")),
        sa.CheckConstraint("set_number > 0", name=op.f("ck_exercise_logs_set_number_positive")),
        sa.CheckConstraint("weight >= 0", name=op.f("ck_exercise_logs_weight_non_negative")),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_logs_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_sessions.id"],
            name=op.f("fk_exercise_logs_session_id_workout_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exercise_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_logs")),
    )
    op.create_index(
        op.f("ix_exercise_logs_exercise_id"), "exercise_logs", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_logs_session_id"), "exercise_logs", ["session_id"], unique=False
    )
    op.create_index(
        "ix_exercise_logs_user_exercise_time",
        "exercise_logs",
        ["user_id", "exercise_id", "performed_at"],
        unique=False,
    )
    op.create_table(
        "health_samples",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "heart_rate",
                "calories",
                "duration",
                name="healthsampletype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "type IN ('heart_rate', 'calories', 'duration')", name=op.f("ck_health_samples_type")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_sessions.id"],
            name=op.f("fk_health_samples_session_id_workout_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_health_samples_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_samples")),
    )
    op.create_index(
        op.f("ix_health_samples_session_id"), "health_samples", ["session_id"], unique=False
    )
    op.create_index(
        "ix_health_samples_user_time", "health_samples", ["user_id", "recorded_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_health_samples_user_time", table_name="health_samples")
    op.drop_index(op.f("ix_health_samples_session_id"), table_name="health_samples")
    op.drop_table("health_samples")
    op.drop_index("ix_exercise_logs_user_exercise_time", table_name="exercise_logs")
    op.drop_index(op.f("ix_exercise_logs_session_id"), table_name="exercise_logs")
    op.drop_index(op.f("ix_exercise_logs_exercise_id"), table_name="exercise_logs")
    op.drop_table("exercise_logs")
    op.drop_index(op.f("ix_workout_sessions_user_id"), table_name="workout_sessions")
    op.drop_index(op.f("ix_workout_sessions_day_id"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index(op.f("ix_exercises_day_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_workout_days_plan_id"), table_name="workout_days")
    op.drop_table("workout_days")
    op.drop_index(
        "uq_workout_plans_one_active_per_user",
        table_name="workout_plans",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_workout_plans_user_id"), table_name="workout_plans")
    op.drop_table("workout_plans")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("users")
    # ### end Alembic commands ###
