"""soft delete workout plans

Revision ID: cea7b3702cad
Revises: 1542b8c6b082
Create Date: 2026-09-28 21:45:29.912121

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cea7b3702cad"
down_revision: str | Sequence[str] | None = "1542b8c6b082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_plans", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_plans", "deleted_at")
    # ### end Alembic commands ###
