"""body data sources

Weighings can come from the data sources (the scale's app writes them into the phone's health
app): two more sources for ``body_measurements``, a switch per connection, and a marker for a
weighing the user deleted, so that a bridge sending it again doesn't bring it back.

The previous release keeps working on what exists when this runs. It doesn't know the new
sources, though: an account that receives weighings from a data source and is then rolled back
gets an error on its body weight screen until the release goes forward again. Nothing is lost.

Revision ID: bca4b41e71fe
Revises: ec1c3006fdb5
Create Date: 2026-10-01 23:02:19.946134

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bca4b41e71fe"
down_revision: str | Sequence[str] | None = "ec1c3006fdb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "body_measurements", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "health_connections",
        sa.Column("body", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't see CHECK constraints.
    op.drop_constraint(op.f("ck_body_measurements_source"), "body_measurements", type_="check")
    op.create_check_constraint(
        op.f("ck_body_measurements_source"),
        "body_measurements",
        "source IN ('manual', 'scale', 'apple_health', 'health_connect')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM body_measurements WHERE source NOT IN ('manual', 'scale')")
    op.drop_constraint(op.f("ck_body_measurements_source"), "body_measurements", type_="check")
    op.create_check_constraint(
        op.f("ck_body_measurements_source"), "body_measurements", "source IN ('manual', 'scale')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_connections", "body")
    op.drop_column("body_measurements", "deleted_at")
    # ### end Alembic commands ###
