"""apple health connection

Revision ID: cebb99a86963
Revises: 0cd1d605ffef
Create Date: 2026-09-28 22:53:50.699366

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cebb99a86963"
down_revision: str | Sequence[str] | None = "0cd1d605ffef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_connections",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heart_rate", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("calories", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_health_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_health_connections")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_health_connections_token_hash")),
    )
    op.create_index(
        "uq_health_samples_user_type_time",
        "health_samples",
        ["user_id", "type", "recorded_at"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_health_samples_user_type_time", table_name="health_samples")
    op.drop_table("health_connections")
    # ### end Alembic commands ###
