/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthWelcomeRouteImport } from './routes/_auth/welcome'
import { Route as AppProgressIndexRouteImport } from './routes/_app/progress/index'
import { Route as AppProgressCalendarRouteImport } from './routes/_app/progress/calendar'
import { Route as AppProgressWeeksRouteImport } from './routes/_app/progress/weeks'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsPasswordRouteImport } from './routes/_app/settings/password'
import { Route as AppSettingsPdfsRouteImport } from './routes/_app/settings/pdfs'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsTimezoneRouteImport } from './routes/_app/settings/timezone'
import { Route as AppWorkoutsIndexRouteImport } from './routes/_app/workouts/index'
import { Route as AppWorkoutsImportRouteImport } from './routes/_app/workouts/import'
import { Route as AppProgressExercisesExerciseIdRouteImport } from './routes/_app/progress/exercises/$exerciseId'
import { Route as AppWorkoutsPlanIdIndexRouteImport } from './routes/_app/workouts/$planId/index'
import { Route as AppWorkoutsPlanIdDaysDayIdIndexRouteImport } from './routes/_app/workouts/$planId/days/$dayId/index'
import { Route as AppWorkoutsPlanIdDaysDayIdExerciseIdRouteImport } from './routes/_app/workouts/$planId/days/$dayId/$exerciseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AppProgressIndexRoute = AppProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressCalendarRoute = AppProgressCalendarRouteImport.update({
  id: '/progress/calendar',
  path: '/progress/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressWeeksRoute = AppProgressWeeksRouteImport.update({
  id: '/progress/weeks',
  path: '/progress/weeks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPasswordRoute = AppSettingsPasswordRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPdfsRoute = AppSettingsPdfsRouteImport.update({
  id: '/settings/pdfs',
  path: '/settings/pdfs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTimezoneRoute = AppSettingsTimezoneRouteImport.update({
  id: '/settings/timezone',
  path: '/settings/timezone',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsImportRoute = AppWorkoutsImportRouteImport.update({
  id: '/workouts/import',
  path: '/workouts/import',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressExercisesExerciseIdRoute =
  AppProgressExercisesExerciseIdRouteImport.update({
    id: '/progress/exercises/$exerciseId',
    path: '/progress/exercises/$exerciseId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkoutsPlanIdIndexRoute = AppWorkoutsPlanIdIndexRouteImport.update({
  id: '/workouts/$planId/',
  path: '/workouts/$planId/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsPlanIdDaysDayIdIndexRoute =
  AppWorkoutsPlanIdDaysDayIdIndexRouteImport.update({
    id: '/workouts/$planId/days/$dayId/',
    path: '/workouts/$planId/days/$dayId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkoutsPlanIdDaysDayIdExerciseIdRoute =
  AppWorkoutsPlanIdDaysDayIdExerciseIdRouteImport.update({
    id: '/workouts/$planId/days/$dayId/$exerciseId',
    path: '/workouts/$planId/days/$dayId/$exerciseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/welcome': typeof AuthWelcomeRoute
  '/progress/calendar': typeof AppProgressCalendarRoute
  '/progress/weeks': typeof AppProgressWeeksRoute
  '/settings/password': typeof AppSettingsPasswordRoute
  '/settings/pdfs': typeof AppSettingsPdfsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/timezone': typeof AppSettingsTimezoneRoute
  '/workouts/import': typeof AppWorkoutsImportRoute
  '/progress/': typeof AppProgressIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workouts/': typeof AppWorkoutsIndexRoute
  '/progress/exercises/$exerciseId': typeof AppProgressExercisesExerciseIdRoute
  '/workouts/$planId/': typeof AppWorkoutsPlanIdIndexRoute
  '/workouts/$planId/days/$dayId/$exerciseId': typeof AppWorkoutsPlanIdDaysDayIdExerciseIdRoute
  '/workouts/$planId/days/$dayId/': typeof AppWorkoutsPlanIdDaysDayIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/welcome': typeof AuthWelcomeRoute
  '/progress/calendar': typeof AppProgressCalendarRoute
  '/progress/weeks': typeof AppProgressWeeksRoute
  '/settings/password': typeof AppSettingsPasswordRoute
  '/settings/pdfs': typeof AppSettingsPdfsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/timezone': typeof AppSettingsTimezoneRoute
  '/workouts/import': typeof AppWorkoutsImportRoute
  '/progress': typeof AppProgressIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workouts': typeof AppWorkoutsIndexRoute
  '/progress/exercises/$exerciseId': typeof AppProgressExercisesExerciseIdRoute
  '/workouts/$planId': typeof AppWorkoutsPlanIdIndexRoute
  '/workouts/$planId/days/$dayId/$exerciseId': typeof AppWorkoutsPlanIdDaysDayIdExerciseIdRoute
  '/workouts/$planId/days/$dayId': typeof AppWorkoutsPlanIdDaysDayIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/welcome': typeof AuthWelcomeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/progress/calendar': typeof AppProgressCalendarRoute
  '/_app/progress/weeks': typeof AppProgressWeeksRoute
  '/_app/settings/password': typeof AppSettingsPasswordRoute
  '/_app/settings/pdfs': typeof AppSettingsPdfsRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/timezone': typeof AppSettingsTimezoneRoute
  '/_app/workouts/import': typeof AppWorkoutsImportRoute
  '/_app/progress/': typeof AppProgressIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workouts/': typeof AppWorkoutsIndexRoute
  '/_app/progress/exercises/$exerciseId': typeof AppProgressExercisesExerciseIdRoute
  '/_app/workouts/$planId/': typeof AppWorkoutsPlanIdIndexRoute
  '/_app/workouts/$planId/days/$dayId/$exerciseId': typeof AppWorkoutsPlanIdDaysDayIdExerciseIdRoute
  '/_app/workouts/$planId/days/$dayId/': typeof AppWorkoutsPlanIdDaysDayIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/welcome'
    | '/progress/calendar'
    | '/progress/weeks'
    | '/settings/password'
    | '/settings/pdfs'
    | '/settings/profile'
    | '/settings/timezone'
    | '/workouts/import'
    | '/progress/'
    | '/settings/'
    | '/workouts/'
    | '/progress/exercises/$exerciseId'
    | '/workouts/$planId/'
    | '/workouts/$planId/days/$dayId/$exerciseId'
    | '/workouts/$planId/days/$dayId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/welcome'
    | '/progress/calendar'
    | '/progress/weeks'
    | '/settings/password'
    | '/settings/pdfs'
    | '/settings/profile'
    | '/settings/timezone'
    | '/workouts/import'
    | '/progress'
    | '/settings'
    | '/workouts'
    | '/progress/exercises/$exerciseId'
    | '/workouts/$planId'
    | '/workouts/$planId/days/$dayId/$exerciseId'
    | '/workouts/$planId/days/$dayId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/reset-password'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/welcome'
    | '/_app/'
    | '/_app/progress/calendar'
    | '/_app/progress/weeks'
    | '/_app/settings/password'
    | '/_app/settings/pdfs'
    | '/_app/settings/profile'
    | '/_app/settings/timezone'
    | '/_app/workouts/import'
    | '/_app/progress/'
    | '/_app/settings/'
    | '/_app/workouts/'
    | '/_app/progress/exercises/$exerciseId'
    | '/_app/workouts/$planId/'
    | '/_app/workouts/$planId/days/$dayId/$exerciseId'
    | '/_app/workouts/$planId/days/$dayId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/progress/': {
      id: '/_app/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof AppProgressIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress/calendar': {
      id: '/_app/progress/calendar'
      path: '/progress/calendar'
      fullPath: '/progress/calendar'
      preLoaderRoute: typeof AppProgressCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress/weeks': {
      id: '/_app/progress/weeks'
      path: '/progress/weeks'
      fullPath: '/progress/weeks'
      preLoaderRoute: typeof AppProgressWeeksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/password': {
      id: '/_app/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AppSettingsPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/pdfs': {
      id: '/_app/settings/pdfs'
      path: '/settings/pdfs'
      fullPath: '/settings/pdfs'
      preLoaderRoute: typeof AppSettingsPdfsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/timezone': {
      id: '/_app/settings/timezone'
      path: '/settings/timezone'
      fullPath: '/settings/timezone'
      preLoaderRoute: typeof AppSettingsTimezoneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/': {
      id: '/_app/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/import': {
      id: '/_app/workouts/import'
      path: '/workouts/import'
      fullPath: '/workouts/import'
      preLoaderRoute: typeof AppWorkoutsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress/exercises/$exerciseId': {
      id: '/_app/progress/exercises/$exerciseId'
      path: '/progress/exercises/$exerciseId'
      fullPath: '/progress/exercises/$exerciseId'
      preLoaderRoute: typeof AppProgressExercisesExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/$planId/': {
      id: '/_app/workouts/$planId/'
      path: '/workouts/$planId'
      fullPath: '/workouts/$planId/'
      preLoaderRoute: typeof AppWorkoutsPlanIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/$planId/days/$dayId/': {
      id: '/_app/workouts/$planId/days/$dayId/'
      path: '/workouts/$planId/days/$dayId'
      fullPath: '/workouts/$planId/days/$dayId/'
      preLoaderRoute: typeof AppWorkoutsPlanIdDaysDayIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/$planId/days/$dayId/$exerciseId': {
      id: '/_app/workouts/$planId/days/$dayId/$exerciseId'
      path: '/workouts/$planId/days/$dayId/$exerciseId'
      fullPath: '/workouts/$planId/days/$dayId/$exerciseId'
      preLoaderRoute: typeof AppWorkoutsPlanIdDaysDayIdExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProgressCalendarRoute: typeof AppProgressCalendarRoute
  AppProgressWeeksRoute: typeof AppProgressWeeksRoute
  AppSettingsPasswordRoute: typeof AppSettingsPasswordRoute
  AppSettingsPdfsRoute: typeof AppSettingsPdfsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsTimezoneRoute: typeof AppSettingsTimezoneRoute
  AppWorkoutsImportRoute: typeof AppWorkoutsImportRoute
  AppProgressIndexRoute: typeof AppProgressIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
  AppProgressExercisesExerciseIdRoute: typeof AppProgressExercisesExerciseIdRoute
  AppWorkoutsPlanIdIndexRoute: typeof AppWorkoutsPlanIdIndexRoute
  AppWorkoutsPlanIdDaysDayIdExerciseIdRoute: typeof AppWorkoutsPlanIdDaysDayIdExerciseIdRoute
  AppWorkoutsPlanIdDaysDayIdIndexRoute: typeof AppWorkoutsPlanIdDaysDayIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProgressCalendarRoute: AppProgressCalendarRoute,
  AppProgressWeeksRoute: AppProgressWeeksRoute,
  AppSettingsPasswordRoute: AppSettingsPasswordRoute,
  AppSettingsPdfsRoute: AppSettingsPdfsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsTimezoneRoute: AppSettingsTimezoneRoute,
  AppWorkoutsImportRoute: AppWorkoutsImportRoute,
  AppProgressIndexRoute: AppProgressIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
  AppProgressExercisesExerciseIdRoute: AppProgressExercisesExerciseIdRoute,
  AppWorkoutsPlanIdIndexRoute: AppWorkoutsPlanIdIndexRoute,
  AppWorkoutsPlanIdDaysDayIdExerciseIdRoute:
    AppWorkoutsPlanIdDaysDayIdExerciseIdRoute,
  AppWorkoutsPlanIdDaysDayIdIndexRoute: AppWorkoutsPlanIdDaysDayIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
